<?php

function islandora_harvester_menu() {
  $path = drupal_get_path('module', 'islandora_harvester');
  $items['islandora/harvest'] = array(
    'title' => 'Harvest Items for Repository',
    'description' => 'Retrieve items from OAI or CSV for ingestion',
    'page callback' => 'ingest_page',
    'access arguments' => array('harvest OAI'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['oai/ahah'] = array(
    'page callback' => 'update_oai_div',
    'access arguments' => array('view fedora collection'),
    'type' => MENU_CALLBACK,
  );

  $items['oai/source/update'] = array(
    'file' => "/harvest_form.inc",
    'page callback' => 'update_source_div',
    'access arguments' => array('view fedora collection'),
    'type' => MENU_CALLBACK,
  );
  $items['oai/destination/update'] = array(
    'file' => "/harvest_form.inc",
    'page callback' => 'update_destination_div',
    'access arguments' => array('view fedora collection'),
    'type' => MENU_CALLBACK,
  );

  $items['islandora/collection/harvest'] = array(
    'title' => t('Harvest into Collection'),
    'page callback' => 'get_collection_harvest_form',
    'type' => MENU_CALLBACK,
    'access arguments' => array('harvest into collection'),
  );
  return $items;
}

function islandora_harvester_perm() {
  return array(
    'harvest OAI',
    'harvest into collection'
  );
}

function ingest_page() {
  module_load_include('inc', 'islandora_harvester', "harvest_form");
  $output = t('Ingest Metadata');
  $output .= drupal_get_form('oai_ingest_form');
  return $output;
}

function islandora_harvester_islandora_collection_mangement($pid) {
  global $user;
  if (user_access('harvest OAI')) {
    return l('Harvest Items for repository', "islandora/collection/harvest/$pid");
  }
}

function get_collection_harvest_form($pid) {
  module_load_include('inc', 'islandora_harvester', "harvest_form");
  return drupal_get_form('oai_ingest_form', $pid);
}